Repository enflujo/imagina-maternoinfantil, pull requests merged in 2022-09, with the labels that each got.

#59 Agregar párrafos a información de ficha técnica
  src/componentes/FichaTecnica.vue
  src/componentes/LineaTiempo.vue
  src/utilidades/fuentes.js
Labels: front-end :art:

#62 💄 Arreglos encabezado
  src/assets/_constantes.scss
  src/componentes/SeccionEncabezado.vue
Labels: front-end :art:

#63 ✨ Agregar logos
  src/assets/imgs/logo_andes_imagina.svg
  src/assets/imgs/logo_enflujo.svg
  src/assets/imgs/logo_f_exito.svg
  src/componentes/GuardaEscobas.vue
  src/vistas/VistaTablero.vue
Labels: front-end :art:

#65 Lista
  src/componentes/ModuloLista.vue
Labels: ui :ocean:

#66 Nuevo diseño de Historias
  src/assets/_constantes.scss
  src/componentes/GuardaEscobas.vue
  src/componentes/LineaDeTiempo/LeyendaElemento.vue
  src/componentes/ModuloLista.vue
  src/vistas/VistaHistorias.vue
Labels: front-end :art:

#67 ✏️ Nuevos créditos
  src/vistas/VistaCreditos.vue
Labels: front-end :art:

#70 ⚗️ arregla Cerrar ficha técnica al hacer click en cualquier parte #24
  src/cerebro/globales.js
  src/componentes/FichaTecnica.vue
  src/componentes/MenuAños.vue
  src/utilidades/ayudas.js
  src/vistas/VistaCreditos.vue
  src/vistas/VistaTablero.vue
Labels: mejora :ant:

#71 💄 Hacer historias responsivas
  src/componentes/SeccionGuardaescobas.vue
  src/vistas/VistaHistorias.vue
Labels: front-end :art:, ui :ocean:

#72 🐛 Arreglar lugar duplicado al seleccionar en mapa
  src/componentes/MapaElemento.vue
Labels: bicho :bug:

#77 :nail_care: Arreglos lista y detalle datos
  src/componentes/DetalleDatos.vue
  src/componentes/LineaDeTiempo/LineaDatos.vue
  src/componentes/LineaTiempo.vue
  src/componentes/MapaElemento.vue
  src/componentes/ModuloLista.vue
  src/vistas/VistaCreditos.vue
Labels: front-end :art:, optimización :zap:, ui :ocean:

#79 🐛 Arreglar botones, lista en celular y otros
  src/componentes/DetalleDatos.vue
  src/componentes/LineaTiempo.vue
  src/componentes/MapaElemento.vue
  src/componentes/ModuloLista.vue
  src/utilidades/frases.js
Labels: bicho :bug:, front-end :art:, ui :ocean:

#76 🙈 Cambios mínimos en el diseño
  src/assets/imgs/bajada.svg
  src/assets/imgs/logo_andes_imagina.svg
  src/assets/imgs/subida.svg
  src/componentes/LineaTiempo.vue
  src/componentes/MapaElemento.vue
  src/componentes/SeccionEncabezado.vue
  src/rutas/index.js
  src/vistas/VistaCreditos.vue
  src/vistas/VistaDatos.vue
  src/vistas/VistaTablero.vue
Labels: front-end :art:

#81 :speech_balloon: Buscador fuzzy
  package.json
  src/componentes/BuscadorLugares.vue
  src/componentes/DetalleDatos.vue
  src/componentes/ModuloLista.vue
  src/vistas/VistaTablero.vue
  yarn.lock
Labels: front-end :art:, optimización :zap:, ui :ocean:
