Repository enflujo/imagina-maternoinfantil, pull requests merged in 2022-07, with the labels that each got.

#16 Linea tiempo y nombres de lugares
  src/componentes/LineaTiempo.vue
  src/componentes/MapaElemento.vue
  src/componentes/MenuIndicadores.vue
  src/utilidades/lugaresDeColombia.js
  src/vistas/VistaTablero.vue
Labels: front-end :art:, ui :ocean:

#18 Comparar lugares
  index.html
  src/App.vue
  src/cerebro/counter.js
  src/cerebro/indicador.js
  src/componentes/LineaTiempo.vue
  src/componentes/MapaElemento.vue
  src/main.js
  src/utilidades/procesador.js
  src/vistas/VistaTablero.vue
Labels: optimización :zap:

#20 Estructura indicadores
  src/utilidades/fuentes.js
Labels: api :evergreen_tree:

#22 ⚡️ Borrar código que reemplaza nombres de lugares
  src/cerebro/datos.js
  src/componentes/ModuloLista.vue
Labels: optimización :zap:
